import argparse
import csv
import json
import os
import random
import re
import time
from dataclasses import dataclass
from typing import Optional, Tuple

import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

# ВАЖНО: запускай из корня проекта, чтобы импорт работал:
# python -m skin_bot.tools.enrich_goldapple
from skin_bot.data.products import PRODUCTS


SEARCH_URL = "https://goldapple.ru/search"
PRODUCT_BASE = "https://goldapple.ru"


@dataclass
class Found:
    ga_id: str
    slug: Optional[str]
    product_url: str


def clean_query(name: str) -> str:
    # убираем скобки и хвосты, мешающие поиску
    s = re.sub(r"\([^)]*\)", "", name).strip()
    s = re.sub(r"\s{2,}", " ", s)
    return s


def make_session() -> requests.Session:
    s = requests.Session()
    s.headers.update({
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                      "AppleWebKit/537.36 (KHTML, like Gecko) "
                      "Chrome/122.0 Safari/537.36",
        "Accept-Language": "ru-RU,ru;q=0.9,en;q=0.8",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Connection": "keep-alive",
    })

    retry = Retry(
        total=5,
        backoff_factor=1.0,
        status_forcelist=[429, 500, 502, 503, 504],
        allowed_methods=["GET"],
        raise_on_status=False,
    )
    adapter = HTTPAdapter(max_retries=retry, pool_connections=10, pool_maxsize=10)
    s.mount("https://", adapter)
    s.mount("http://", adapter)
    return s


def parse_first_product_from_html(html: str) -> Optional[Found]:
    """
    Ищем любую ссылку на карточку: /<digits>-<slug> или /<digits>
    На практике в выдаче часто встречается /19000...-slug
    """
    # Сначала ищем полный формат /12345678-slug
    m = re.search(r'href="(/(\d{8,})-([a-z0-9\-]+))"', html)
    if m:
        path = m.group(1)
        ga_id = m.group(2)
        slug = m.group(3)
        return Found(ga_id=ga_id, slug=slug, product_url=PRODUCT_BASE + path)

    # Потом упрощённый /12345678 (иногда встречается)
    m2 = re.search(r'href="(/(\d{8,}))"', html)
    if m2:
        path = m2.group(1)
        ga_id = m2.group(2)
        return Found(ga_id=ga_id, slug=None, product_url=PRODUCT_BASE + path)

    return None


def search_product(session: requests.Session, query: str, timeout: int = 20) -> Tuple[Optional[Found], str]:
    """
    Возвращает (Found|None, debug_info)
    """
    params = {"text": query}
    r = session.get(SEARCH_URL, params=params, timeout=timeout)
    dbg = f"status={r.status_code} url={r.url}"

    # Иногда могут вернуть антибот страницу — тогда парсер ничего не найдёт
    found = parse_first_product_from_html(r.text)
    return found, dbg


def verify_product_page(session: requests.Session, url: str, timeout: int = 20) -> bool:
    """
    Проверяем, что карточка реально открывается:
    - статус 200
    - не редиректит на главную
    """
    r = session.get(url, timeout=timeout, allow_redirects=True)
    if r.status_code != 200:
        return False

    # Если нас унесло на главную или на /web — считаем "не ок"
    final_url = str(r.url)
    if final_url.rstrip("/") in ("https://goldapple.ru", "https://goldapple.ru/"):
        return False
    if "/web" in final_url and "q=" not in final_url:
        return False

    return True


def dump_products_py(products: list[dict], out_path: str) -> None:
    """
    Пишем новый файл products_enriched.py с PRODUCTS = [...]
    """
    import pprint
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    # Чтобы вывод был более читаемым
    formatted = pprint.pformat(products, width=120, sort_dicts=False)

    content = "# Auto-generated by enrich_goldapple.py\n\nPRODUCTS = " + formatted + "\n"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sleep", type=float, default=1.2, help="Пауза между запросами (сек).")
    ap.add_argument("--jitter", type=float, default=0.6, help="Случайный джиттер к паузе (сек).")
    ap.add_argument("--max-items", type=int, default=10_000, help="Лимит обработанных товаров.")
    ap.add_argument("--dry-run", action="store_true", help="Ничего не записывать, только отчёт.")
    ap.add_argument("--verify-card", action="store_true", help="Проверять открытие карточки (медленнее, но точнее).")
    ap.add_argument("--out-py", default="skin_bot/data/products_enriched.py", help="Куда писать новый products.py.")
    ap.add_argument("--report-dir", default="reports", help="Папка отчётов.")
    args = ap.parse_args()

    session = make_session()

    os.makedirs(args.report_dir, exist_ok=True)
    report_csv = os.path.join(args.report_dir, "goldapple_report.csv")
    report_json = os.path.join(args.report_dir, "goldapple_report.json")

    updated = 0
    processed = 0
    report_rows = []
    new_products = []

    for p in PRODUCTS:
        processed += 1
        if processed > args.max_items:
            break

        # Всегда сохраняем исходный объект (копию), чтобы не портить импортируемый PRODUCTS
        item = dict(p)

        # Запрос только если нет deeplink_ok
        if item.get("deeplink_ok") is True:
            new_products.append(item)
            report_rows.append({
                "name": item.get("name", ""),
                "query": item.get("query", ""),
                "status": "SKIP_ALREADY_OK",
                "ga_id": item.get("ga_id", ""),
                "slug": item.get("slug", ""),
                "product_url": "",
                "debug": "",
            })
            continue

        query = item.get("query") or clean_query(item.get("name", ""))
        item["query"] = query  # закрепим query всегда

        found, dbg = search_product(session, query)

        if not found:
            # Не найдено — оставляем без deeplink_ok, будет поиск
            item.pop("deeplink_ok", None)
            report_rows.append({
                "name": item.get("name", ""),
                "query": query,
                "status": "NOT_FOUND",
                "ga_id": item.get("ga_id", ""),
                "slug": item.get("slug", ""),
                "product_url": "",
                "debug": dbg,
            })
            new_products.append(item)
        else:
            ok = True
            if args.verify_card:
                ok = verify_product_page(session, found.product_url)

            if ok:
                item["ga_id"] = found.ga_id
                if found.slug:
                    item["slug"] = found.slug
                item["deeplink_ok"] = True
                updated += 1
                status = "FOUND_OK"
            else:
                # Карточка не открылась надежно — лучше не ставить deeplink_ok
                item["ga_id"] = found.ga_id
                if found.slug:
                    item["slug"] = found.slug
                item.pop("deeplink_ok", None)
                status = "FOUND_BUT_NOT_OK"

            report_rows.append({
                "name": item.get("name", ""),
                "query": query,
                "status": status,
                "ga_id": item.get("ga_id", ""),
                "slug": item.get("slug", ""),
                "product_url": found.product_url,
                "debug": dbg,
            })
            new_products.append(item)

        # Пауза с джиттером, чтобы не словить блокировку
        time.sleep(args.sleep + random.random() * args.jitter)

    # Запись отчётов
    with open(report_json, "w", encoding="utf-8") as f:
        json.dump(report_rows, f, ensure_ascii=False, indent=2)

    with open(report_csv, "w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["name", "query", "status", "ga_id", "slug", "product_url", "debug"])
        w.writeheader()
        w.writerows(report_rows)

    if not args.dry_run:
        dump_products_py(new_products, args.out_py)

    print(f"Processed: {processed}, Updated deeplink_ok: {updated}")
    print(f"Report CSV: {report_csv}")
    print(f"Report JSON: {report_json}")
    if not args.dry_run:
        print(f"Enriched products file: {args.out_py}")


if __name__ == "__main__":
    main()
